sudo: false
language: python
cache: pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
    - language: generic
      python: 2.7
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n py27 python=2.7 -y
      install:
        - source activate py27
        - pip install tox
        - conda install -y --name py27 virtualenv
      script: tox -e py27

    - language: generic
      python: 3.4
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n py34 python=3.4 -y
      install:
        - source activate py34
        - pip install tox
        - conda install -y --name py34 virtualenv
      script: tox -e py34

    - language: generic
      python: 3.5
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n py35 python=3.5 -y
      install:
        - source activate py35
        - pip install tox
        - conda install -y --name py35 virtualenv
      script: tox -e py35

    - language: generic
      python: 3.6
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - pip install tox
        - conda install -y --name py36 virtualenv
      script: tox -e py36
install:
  - pip install tox-travis

script: tox
