build: false

environment:
  matrix:
    - PYTHON: "C:/Python37"


init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python37"

install:
  - "%PYTHON%/Scripts/pip.exe install wheel tox"
  - "%PYTHON%/Scripts/pip.exe install cryptography --only-binary=:all:"
  - "%PYTHON%/Scripts/pip.exe install -r requirements_dev.txt"
  - "%PYTHON%/Scripts/pip.exe install -e ."

test_script:
  - "%PYTHON%/python.exe -m pytest"
